[[pages]]
path = "/"
screenshotTimestamp = "2026-04-01T12:08:30Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/a2a0e3c1-ee0a-4e1c-b27b-1a8c2466b530/43f3a8be-06ff-4a06-871a-70bb21206dd7/2B1r7xZ"
